exclude = ["^https?://(www\\.)?github\\.com", "^https?://discord\\.gg", "^https?://community\\.vuetifyjs\\.com", "invalid.jpg", "^https://mcp\\.vuetifyjs\\.com/mcp", "^https?://.*\\.vuejs\\.org"]

root_dir = "./apps/docs/dist"
