name: Docs Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
      deployments: write
    steps:
      - uses: actions/checkout@v6
      - uses: vuetifyjs/setup-action@master
      - run: pnpm run build:docs
        env:
          VITE_API_SERVER_URL: ${{ vars.API_SERVER_URL }}
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          lycheeVersion: v0.22.0
          args: --config lychee.toml './apps/docs/dist'
          fail: false
      - uses: vuetifyjs/coolify-action@master
        with:
          imageName: v0-docs
          dockerfilePath: ./apps/docs/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN  }}
          coolifyWebhook: ${{ secrets.COOLIFY_WEBHOOK }}
          coolifySecret: ${{ secrets.COOLIFY_TOKEN }}
